services:
  - docker

install: docker-compose run js-build npm install

script:
  - docker-compose run js-build npm run lint:js
  - docker-compose run js-build npm run lint:css
  - docker-compose run js-build npm run test
  - docker-compose run js-build npm run build

notifications:
  email:
    on_success: change
    on_failure: always

cache:
  directories:
    - "node_modules"
