services:
  - docker

install: docker-compose run js-build npm install

script:
  - docker-compose run js-build npm run lint
  - docker-compose run js-build npm run build

notifications:
  email:
    on_success: change
    on_failure: always

cache:
  directories:
    - "node_modules"
