# A Campaign with global settings
[desktop]
campaign_tracking = "07-ba-170914"

# Banners of the campaign, key after "banners" can be anything
[desktop.banners.ctrl]
filename = "./desktop/banner_ctrl.js"
pagename = "B17WMDE_07_170913_ctrl"
tracking = "org-07-170914-ctrl"

[desktop.banners.var]
filename = "./desktop/banner_var.js"
pagename = "B17WMDE_07_170913_var"
tracking = "org-07-170914-var"

[mobile]
campaign_tracking = "mob01-ba-170904"
preview_skin = "minerva"

[mobile.banners.ctrl]
filename = "./mobile/banner_ctrl.js"
pagename = "B17WMDE_mob_01_170904_ctrl"
tracking = "org-mob01-170904-ctrl"

[mobile.banners.var]
filename = "./mobile/banner_var.js"
pagename = "B17WMDE_mob_01_170904_var"
tracking = "org-mob01-170904-var"
