# A Campaign with global settings
[desktop]
campaign_tracking = "08-ba-170928"

# Banners of the campaign, key after "banners" can be anything
[desktop.banners.ctrl]
filename = "./desktop/banner_ctrl.js"
pagename = "B17WMDE_08_170928_ctrl"
tracking = "org-08-170928-ctrl"

[desktop.banners.var]
filename = "./desktop/banner_var.js"
pagename = "B17WMDE_08_170928_var"
tracking = "org-08-170928-var"

[mobile]
campaign_tracking = "mob01-ba-170904"
preview_skin = "minerva"

[mobile.banners.ctrl]
filename = "./mobile/banner_ctrl.js"
pagename = "B17WMDE_mob_01_170904_ctrl"
tracking = "org-mob01-170904-ctrl"

[mobile.banners.var]
filename = "./mobile/banner_var.js"
pagename = "B17WMDE_mob_01_170904_var"
tracking = "org-mob01-170904-var"
