# A Campaign with global settings
[desktop]
campaign_tracking = "05-ba-170825"

# Banners of the campaign, key after "banners" can be anything
[desktop.banners.ctrl]
filename = "./desktop/banner_ctrl.js"
pagename = "B17WMDE_05_170825_ctrl"
tracking = "org-05-170825-ctrl"

[desktop.banners.var]
filename = "./desktop/banner_var.js"
pagename = "B17WMDE_05_170825_var"
tracking = "org-05-170825-var"

[desktop.banners.prototype]
filename = "./desktop/banner_prototype.js"
pagename = "B17WMDE_06_170905_prototype"
tracking = "org-06-170905-prototype"

[mobile]
campaign_tracking = "mob01-ba-170904"
preview_skin = "minerva"

[mobile.banners.ctrl]
filename = "./mobile/banner_ctrl.js"
pagename = "B17WMDE_mob_01_170904_ctrl"
tracking = "org-mob01-170904-ctrl"

[mobile.banners.var]
filename = "./mobile/banner_var.js"
pagename = "B17WMDE_mob_01_170904_var"
tracking = "org-mob01-170904-var"
