# A Campaign with global settings
[desktop]
campaign_tracking = "11-ba-171103"
preview_link = "/wiki/Wikipedia:Hauptseite?banner=B17WMDE_webpack_prototype&devbanner={{banner}}"

# Banners of the campaign, key after "banners" can be anything
[desktop.banners.ctrl]
filename = "./desktop/banner_ctrl.js"
pagename = "B17WMDE_11_171103_ctrl"
tracking = "org-11-171103-ctrl"

[desktop.banners.var]
filename = "./desktop/banner_var.js"
pagename = "B17WMDE_11_171103_var"
tracking = "org-11-171103-var"


[mobile]
campaign_tracking = "mob02-ba-171026"
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=minerva&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"

[mobile.banners.ctrl]
filename = "./mobile/banner_ctrl.js"
pagename = "B17WMDE_mob_02_171019_ctrl"
tracking = "org-mob02-171026-ctrl"

[mobile.banners.var]
filename = "./mobile/banner_var.js"
pagename = "B17WMDE_mob_02_171019_var"
tracking = "org-mob02-171026-var"


[wikipediade]
campaign_tracking = "09-ba-171006"
preview_link = "/wikipedia.de?bannertest=Banner/B17WMDE_webpack_prototype&devbanner={{banner}}"

[wikipediade.banners.ctrl]
filename = "./wikipedia.de/banner_ctrl.js"
pagename = "FR2016_09_171007_ctrl"
tracking = "org-09-171006-ctrl"

[wikipediade.banners.var]
filename = "./wikipedia.de/banner_var.js"
pagename = "FR2016_09_171007_var"
tracking = "org-09-171006-var"
