# A Campaign with global settings
[desktop]
campaign_tracking = "13-ba-171111"
preview_link = "/wiki/Wikipedia:Hauptseite?banner=B17WMDE_webpack_prototype&devbanner={{banner}}"

# Banners of the campaign, key after "banners" can be anything
[desktop.banners.ctrl]
filename = "./desktop/banner_ctrl.js"
pagename = "B17WMDE_13_171111_ctrl"
tracking = "org-13-171111-ctrl"

[desktop.banners.var]
filename = "./desktop/banner_var.js"
pagename = "B17WMDE_13_171111_var"
tracking = "org-13-171111-var"


[mobile]
campaign_tracking = "mob03-ba-171110"
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=minerva&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"

[mobile.banners.ctrl]
filename = "./mobile/banner_ctrl.js"
pagename = "B17WMDE_mob_03_171110_ctrl"
tracking = "org-mob03-171110-ctrl"

[mobile.banners.var]
filename = "./mobile/banner_var.js"
pagename = "B17WMDE_mob_03_171110_var"
tracking = "org-mob03-171110-var"


[pad]
campaign_tracking = "pad01-ba-171117"
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=minerva&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"

[pad.banners.ctrl]
filename = "./pad/banner_ctrl.js"
pagename = "B17WMDE_pad_01_171116_ctrl"
tracking = "org-pad01-171117-ctrl"

[pad.banners.pad]
filename = "./pad/banner_var.js"
pagename = "B17WMDE_pad_01_171116_var"
tracking = "org-pad01-171117-var"


[wikipediade]
campaign_tracking = "09-ba-171006"
preview_link = "/wikipedia.de?bannertest=Banner/B17WMDE_webpack_prototype&devbanner={{banner}}"

[wikipediade.banners.ctrl]
filename = "./wikipedia.de/banner_ctrl.js"
pagename = "FR2016_09_171007_ctrl"
tracking = "org-09-171006-ctrl"

[wikipediade.banners.var]
filename = "./wikipedia.de/banner_var.js"
pagename = "FR2016_09_171007_var"
tracking = "org-09-171006-var"
