# A Campaign with global settings
[desktop]
campaign_tracking = "05-ba-170825"

# Banners of the campaign, key after "banners" can be anything
[desktop.banners.ctrl]
filename = "./desktop/banner_ctrl.js"
pagename = "B17WMDE_05_170824_ctrl"
tracking = "org-05-170825-ctrl"

[desktop.banners.var]
filename = "./desktop/banner_var.js"
pagename = "B17WMDE_05_170824_var"
tracking = "org-05-170825-var"

[mobile]
campaign_tracking = "mob01-ba-170829"

[mobile.banners.ctrl]
filename = "./mobile/banner_ctrl.js"
pagename = "B17WMDE_mob01_170829_ctrl"
tracking = "org-mob01-170829-ctrl"

[mobile.banners.var]
filename = "./mobile/banner_var.js"
pagename = "B17WMDE_mob01_170829_var"
tracking = "org-mob01-170829-var"
