# A Campaign with global settings
[desktop]
campaign_tracking = "37-ba-171222"
preview_link = "/wiki/Wikipedia:Hauptseite?banner=B17WMDE_webpack_prototype&devbanner={{banner}}"

# Banners of the campaign, key after "banners" can be anything
[desktop.banners.ctrl]
filename = "./desktop/banner_ctrl.js"
pagename = "B17WMDE_37_171221_ctrl"
tracking = "org-37-171222-ctrl"

[desktop.banners.var]
filename = "./desktop/banner_var.js"
pagename = "B17WMDE_37_171221_var"
tracking = "org-37-171222-var"

[dewiki-default]
campaign_tracking = "ca17-default"
preview_link = "/wiki/Wikipedia:Hauptseite?banner=B17WMDE_webpack_prototype&devbanner={{banner}}"

[dewiki-default.banners.default]
filename = "./desktop/banner_ctrl.js"
pagename = "B17WMDE_dewiki_desktop_default"
tracking = "org-desktop-de-171113"


# Mobile Campaign
[mobile]
campaign_tracking = "mob05-ba-171218"
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=minerva&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"

[mobile.banners.ctrl]
filename = "./mobile/banner_ctrl.js"
pagename = "B17WMDE_mob_05_171218_ctrl"
tracking = "org-mob05-171218-ctrl"

[mobile.banners.var]
filename = "./mobile/banner_var.js"
pagename = "B17WMDE_mob_05_171218_var"
tracking = "org-mob05-171218-var"

# Default mobile campaign
[mobile-default]
campaign_tracking = "ca17-default"
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=minerva&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"

[mobile-default.banners.default]
filename = "./mobile/banner_ctrl.js"
pagename = "B17WMDE_dewiki_mobile_default"
tracking = "org-mob-de-171121"


# iPad campaign
[pad]
campaign_tracking = "pad04-ba-171218"
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=minerva&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"

[pad.banners.ctrl]
filename = "./pad/banner_ctrl.js"
pagename = "B17WMDE_pad_04_171218_ctrl"
tracking = "org-pad04-171218-ctrl"

[pad.banners.pad]
filename = "./pad/banner_var.js"
pagename = "B17WMDE_pad_04_171218_var"
tracking = "org-pad04-171218-var"

# Default ipad campaign
[pad-default]
campaign_tracking = "ca17-default"
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=minerva&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"

[pad-default.banners.default]
filename = "./pad/banner_ctrl.js"
pagename = "B17WMDE_dewiki_ipad_default"
tracking = "org-pad-de-171121"


# Wikipedia.de Campaign
[wikipediade]
campaign_tracking = "wpde-01-171111"
preview_link = "/wikipedia.de?bannertest=Banner/B17WMDE_webpack_prototype&devbanner={{banner}}"

[wikipediade.banners.ctrl]
filename = "./wikipedia.de/banner_ctrl.js"
pagename = "B17WPDE_01_171111_ctrl"
tracking = "wpde-01-171111-ctrl"

[wikipediade.banners.var]
filename = "./wikipedia.de/banner_var.js"
pagename = "B17WPDE_01_171111_var"
tracking = "wpde-01-171111-var"


# English Campaign
[english]
campaign_tracking = "en03-ba-171218"
preview_link = "/wiki/Wikipedia:Hauptseite?banner=B17WMDE_webpack_prototype&devbanner={{banner}}"

[english.banners.ctrl]
filename = "./english/banner_ctrl.js"
pagename = "B17WMDE_en03_171218_ctrl"
tracking = "org-en03-171218-ctrl"

[english.banners.var]
filename = "./english/banner_var.js"
pagename = "B17WMDE_en03_171218_var"
tracking = "org-en03-171218-var"


[enwiki-default]
campaign_tracking = "ca17-default"
preview_link = "/wiki/Wikipedia:Hauptseite?banner=B17WMDE_webpack_prototype&devbanner={{banner}}"

[enwiki-default.banners.default]
filename = "./english/banner_ctrl.js"
pagename = "B17WMDE_enwiki_desktop_default"
tracking = "org-desktop-en-171121"
