# A Campaign with global settings
[desktop]
campaign_tracking = "09-ba-171006"

# Banners of the campaign, key after "banners" can be anything
[desktop.banners.ctrl]
filename = "./desktop/banner_ctrl.js"
pagename = "B17WMDE_09_171006_ctrl"
tracking = "org-09-171006-ctrl"

[desktop.banners.var]
filename = "./desktop/banner_var.js"
pagename = "B17WMDE_09_171006_var"
tracking = "org-09-171006-var"

[mobile]
campaign_tracking = "mob01-ba-170904"
preview_skin = "minerva"

[mobile.banners.ctrl]
filename = "./mobile/banner_ctrl.js"
pagename = "B17WMDE_mob_01_170904_ctrl"
tracking = "org-mob01-170904-ctrl"

[mobile.banners.var]
filename = "./mobile/banner_var.js"
pagename = "B17WMDE_mob_01_170904_var"
tracking = "org-mob01-170904-var"
